<?php
/**
 * all.phtml
 * 
 * @creation  2015-11-13
 * @version   1.0
 * @package   op-core
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright 2014 (C) Tomoaki Nagahara All right reserved.
 */
/* @var $this App */
?>
<?= $this->Template('_social/twitter.phtml') ?>
<?= $this->Template('_social/facebook.phtml') ?>
<?= $this->Template('_social/hatena.phtml') ?>
<?= $this->Template('_social/mixi.phtml') ?>
<?= $this->Template('_social/google+.phtml') ?>
