<?php
/**
 * all.phtml
 * 
 * @creation  2015-11-13
 * @version   1.0
 * @package   op-unit-social
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright 2015 (C) Tomoaki Nagahara All right reserved.
 */
/* @var $this App */
?>
<?= $this->Template('app:/_social/twitter.phtml') ?>
<?= $this->Template('app:/_social/facebook.phtml') ?>
<?= $this->Template('app:/_social/hatena.phtml') ?>
<?= $this->Template('app:/_social/mixi.phtml') ?>
<?= $this->Template('app:/_social/google+.phtml') ?>
