<?php
/**
 * all.phtml
 * 
 * @creation  2015-11-13
 * @version   1.0
 * @package   op-unit-social
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright 2015 (C) Tomoaki Nagahara All right reserved.
 */
/* @var $this App */
?>
<ul id="op-unit-social">
	<li><?= $this->Template('app:/_social/twitter.phtml') ?></li>
	<li><?= $this->Template('app:/_social/facebook.phtml') ?></li>
	<li><?= $this->Template('app:/_social/hatena.phtml') ?></li>
	<li><?= $this->Template('app:/_social/mixi.phtml') ?></li>
	<li><?= $this->Template('app:/_social/google+.phtml') ?></li>
</ul>

<style>
/* social button */
#op-unit-social {
	margin-top: 0;
	padding: 0 0 0 0.5em;
}

#op-unit-social li {
	display: inline-block;
	vertical-align: top;
}

.fb_iframe_widget > span {
	vertical-align: baseline !important;/* adjust vertical align for facebook like button. */
}
</style>
