<?php
/**
 * facebook.phtml
 * 
 * @creation  2015-11-13
 * @version   1.0
 * @package   op-unit-social
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright 2015 (C) Tomoaki Nagahara All right reserved.
 */
/* @var $this App */
?>
<!-- Facebook -->
<div id="fb-root"></div>
<script>(function(d, s, id) {
			var js, fjs = d.getElementsByTagName(s)[0];
			if (d.getElementById(id)) return;
			js = d.createElement(s); js.id = id;
			js.src = "//connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v2.3";
			fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));
</script>
<div class="fb-like"
	 data-href="<?= $this->ConvertURL('./',true) ?>"
	 data-layout="button_count"
	 data-action="like"
	 data-show-faces="false"
	 data-share="false">
</div>
