<?php
/**
 * google+.phtml
 * 
 * @creation  2015-11-13
 * @version   1.0
 * @package   op-core
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright 2014 (C) Tomoaki Nagahara All right reserved.
 */
/* @var $this App */
?>
<!-- Google plusone -->
<script src="https://apis.google.com/js/platform.js" async defer>
	{lang: '<?= $this->i18n()->GetLang('ja') ?>'}
</script>
<div class="g-plusone" data-size="medium"></div>
