<?php
/**
 * twitter.phtml
 * 
 * @creation  2015-11-13
 * @version   1.0
 * @package   op-unit-social
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright 2015 (C) Tomoaki Nagahara All right reserved.
 */
/* @var $this App */
?>
<!-- Twitter -->
<a href="https://twitter.com/share" class="twitter-share-button"> </a>
<script>
	!function(d,s,id){
		var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';
		if(!d.getElementById(id)){
			js=d.createElement(s);
			js.id=id;
			js.src=p+'://platform.twitter.com/widgets.js';
			fjs.parentNode.insertBefore(js,fjs);
		}
	}
	(document, 'script', 'twitter-wjs');
</script>
